config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :allocations

  resources :price_categories

  resources :ticket_categories

  resources :shows

  resources :section_rows

  resources :sections

  resources :venues

  resources :venue_layouts

  resources :event_categories

  resources :events

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/allocation.rb
class Allocation < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/event_category.rb
class EventCategory < ActiveRecord::Base
end

app/models/price_category.rb
class PriceCategory < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/section_row.rb
class SectionRow < ActiveRecord::Base
end

app/models/show.rb
class Show < ActiveRecord::Base
end

app/models/ticket_category.rb
class TicketCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :change_requests
  has_many :change_evaluations
  has_many :authorizations
  before_save { self.email = email.downcase, self.username = username.downcase }
  validates :name, presence: true, length: {maximum: 50}
  validates :username, presence: true, length: {maximum: 20},uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/models/venue_layout.rb
class VenueLayout < ActiveRecord::Base
end

app/controllers/allocations_controller.rb
class AllocationsController < ApplicationController
  before_action :set_allocation, only: [:show, :edit, :update, :destroy]

  # GET /allocations
  # GET /allocations.json
  def index
    @allocations = Allocation.all
  end

  # GET /allocations/1
  # GET /allocations/1.json
  def show
  end

  # GET /allocations/new
  def new
    @allocation = Allocation.new
  end

  # GET /allocations/1/edit
  def edit
  end

  # POST /allocations
  # POST /allocations.json
  def create
    @allocation = Allocation.new(allocation_params)

    respond_to do |format|
      if @allocation.save
        format.html { redirect_to @allocation, notice: 'Allocation was successfully created.' }
        format.json { render :show, status: :created, location: @allocation }
      else
        format.html { render :new }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allocations/1
  # PATCH/PUT /allocations/1.json
  def update
    respond_to do |format|
      if @allocation.update(allocation_params)
        format.html { redirect_to @allocation, notice: 'Allocation was successfully updated.' }
        format.json { render :show, status: :ok, location: @allocation }
      else
        format.html { render :edit }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allocations/1
  # DELETE /allocations/1.json
  def destroy
    @allocation.destroy
    respond_to do |format|
      format.html { redirect_to allocations_url, notice: 'Allocation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allocation
      @allocation = Allocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allocation_params
      params.require(:allocation).permit(:assigned, :user_id, :show_id, :row_id, :quantity, :start_seat, :end_seat)
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController


  def register
    user = User.new(user_params)
    if user.save
      token = AuthToken.issue_token({ user_id: user.id })
      render json: { user: user,
                     token: token }
    else
      render json: { errors: user.errors }
    end
  end

  def authenticate
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      token = AuthToken.issue_token({ user_id: user.id })
      render json: { user: user,
                     token: token }
    else
      render json: { error: "Invalid email/password combination" }, status: :unauthorized
    end
  end



end

app/helpers/allocations_helper.rb
module AllocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{page_title} | #{base_title}"                 # String interpolation
    end
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/section_rows_helper.rb
module SectionRowsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end


  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/allocations/_form.html.erb
<%= form_for(@allocation) do |f| %>
  <% if @allocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allocation.errors.count, "error") %> prohibited this allocation from being saved:</h2>

      <ul>
      <% @allocation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assigned %><br>
    <%= f.text_field :assigned %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :show_id %><br>
    <%= f.number_field :show_id %>
  </div>
  <div class="field">
    <%= f.label :row_id %><br>
    <%= f.number_field :row_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :start_seat %><br>
    <%= f.number_field :start_seat %>
  </div>
  <div class="field">
    <%= f.label :end_seat %><br>
    <%= f.number_field :end_seat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allocations/edit.html.erb
<h1>Editing Allocation</h1>

<%= render 'form' %>

<%= link_to 'Show', @allocation %> |
<%= link_to 'Back', allocations_path %>

app/views/allocations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Allocations</h1>

<table>
  <thead>
    <tr>
      <th>Assigned</th>
      <th>User</th>
      <th>Show</th>
      <th>Row</th>
      <th>Quantity</th>
      <th>Start seat</th>
      <th>End seat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @allocations.each do |allocation| %>
      <tr>
        <td><%= allocation.assigned %></td>
        <td><%= allocation.user_id %></td>
        <td><%= allocation.show_id %></td>
        <td><%= allocation.row_id %></td>
        <td><%= allocation.quantity %></td>
        <td><%= allocation.start_seat %></td>
        <td><%= allocation.end_seat %></td>
        <td><%= link_to 'Show', allocation %></td>
        <td><%= link_to 'Edit', edit_allocation_path(allocation) %></td>
        <td><%= link_to 'Destroy', allocation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allocation', new_allocation_path %>

app/views/allocations/new.html.erb
<h1>New Allocation</h1>

<%= render 'form' %>

<%= link_to 'Back', allocations_path %>

app/views/allocations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assigned:</strong>
  <%= @allocation.assigned %>
</p>

<p>
  <strong>User:</strong>
  <%= @allocation.user_id %>
</p>

<p>
  <strong>Show:</strong>
  <%= @allocation.show_id %>
</p>

<p>
  <strong>Row:</strong>
  <%= @allocation.row_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @allocation.quantity %>
</p>

<p>
  <strong>Start seat:</strong>
  <%= @allocation.start_seat %>
</p>

<p>
  <strong>End seat:</strong>
  <%= @allocation.end_seat %>
</p>

<%= link_to 'Edit', edit_allocation_path(@allocation) %> |
<%= link_to 'Back', allocations_path %>